### ISSUE TITLE
npm start 错误,后端无法启动

### ISSUE THREAD

**Issue by followtheart** [dream-wall/dream-wall#3]
另外一个项目
dream-wall-vue-graphql
有同样的问题

```
dream-wall/server/server.js:18
app.use(async (ctx, next) => {
              ^
SyntaxError: Unexpected token (
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by savoygu** [comment]
应该是 Node 版本的问题，不支持 `async/await`，更新至 8.0 版本以上就行了
